apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermaven-js
  labels:
    app: usermaven-js
spec:
  replicas: 3
  selector:
    matchLabels:
      app: usermaven-js
  template:
    metadata:
      labels:
        app: usermaven-js
    spec:
      containers:
      - name: usermaven-js
        image: ghcr.io/amna0125/usermaven-js-stage:9f3a24eb820929380ab2decda90bbbf8257e5506
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: usermaven-js
  name: usermaven-js-svc
spec:
  ports:
  - name: usermaven-js-port
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: usermaven-js
  type: ClusterIP
status:
  loadBalancer: {}
